listener 8883
allow_anonymous false
password_file /mosquitto/secure/passwords
acl_file /mosquitto/secure/acl
cafile /mosquitto/secure/ca.crt
certfile /mosquitto/secure/server.crt
keyfile /mosquitto/secure/server.key
tls_version tlsv1.2
persistence true
persistence_location /mosquitto/data/
log_dest stdout
max_packet_size 16384

